export const Users = [
  {
    id: 1,
    profilePicture: "person/11.avif",
    username: "Roshan Kumar",
  },
  {
    id: 2,
    profilePicture: "person/12.jpg",
    username: "Rakesh Mishra",
  },
  {
    id: 3,
    profilePicture: "person/13.avif",
    username: "Rajesh Das",
  },
  {
    id: 4,
    profilePicture: "person/14.avif",
    username: "Pritesh Singh",
  },
  {
    id: 5,
    profilePicture: "person/15.avif",
    username: "Lalit Chhetri",
  },
  {
    id: 6,
    profilePicture: "person/16.avif",
    username: "Sachet Joshi",
  },
  {
    id: 7,
    profilePicture: "person/17.avif",
    username: "Mohit Rana",
  },
  {
    id: 8,
    profilePicture: "person/18.avif",
    username: "Ritesh Sahoo",
  },
  {
    id: 9,
    profilePicture: "person/19.avif",
    username: "Jason Mark",
  },
  {
    id: 10,
    profilePicture: "person/20.avif",
    username: "Sohaib Ahmed",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "From another point of view.",
    photo: "post/11.avif",
    date: "5 mins ago",
    userId: 1,
    like: 22,
    comment: 9,
  },
  {
    id: 2,
    photo: "post/12.avif",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "A beautiful distraction.",
    photo: "post/13.avif",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "post/14.avif",
    date: "4 hours ago",
    userId: 4,
    like: 77,
    comment: 3,
  },
  {
    id: 5,
    photo: "post/15.avif",
    date: "5 hours ago",
    userId: 5,
    like: 29,
    comment: 9,
  },
  {
    id: 6,
    photo: "post/16.avif",
    date: "1 day ago",
    userId: 6,
    like: 49,
    comment: 9,
  },
  {
    id: 7,
    desc: "Nature never goes out of style.",
    photo: "post/17.avif",
    date: "2 days ago",
    userId: 7,
    like: 32,
    comment: 3,
  },
  {
    id: 8,
    photo: "post/18.avif",
    date: "3 days ago",
    userId: 8,
    like: 35,
    comment: 3,
  },
  {
    id: 9,
    desc: "I Will keep this view in my heart forever.",
    photo: "post/19.avif",
    date: "5 days ago",
    userId: 9,
    like: 51,
    comment: 2,
  },
  {
    id: 10,
    desc: "I want to wake up to this view every day.",
    photo: "post/20.avif",
    date: "1 week ago",
    userId: 10,
    like: 34,
    comment: 12,
  },
];
